import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";

export const metadata = {
  title: "Quick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-lato`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
